name: GitHub Actions Demo
on: [push]
jobs:
  build :
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install python
        uses : actions/setup-python@v1
        with : 
          python-version : 3.10.7

      - name : install dependencies
        run : |
          python -m pip install --upgrade pip
      
      - name : run test cases of create function
        run : python tests\test_cases_create.py

      - name : run test cases of set function
        run : python tests\test_cases_set.py


